apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
        - name: openhab-container
          image: openhab/openhab:latest
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 8101
            - containerPort: 5007
            - containerPort: 22
          env:
            - name: CRYPTO_POLICY
              value: "unlimited"
            - name: EXTRA_JAVA_OPTS
              value: "-Duser.timezone=Europe/Berlin"
            - name: OPENHAB_HTTP_PORT
              value: "8080"
            - name: OPENHAB_HTTPS_PORT
              value: "8443"
---

apiVersion: v1
kind: Service
metadata:
  name: openhab
spec:
  type: NodePort
  ports:
    # Which port on the node is the service available externallythrough?
    - nodePort: 30001
      # Inside the cluster, what port does the service expose?
      port: 8080
      protocol: TCP
      # Which port do pods selected by this service expose?
      targetPort: 8080
      name: http
#    - nodePort: 8443
#      port: 8443
#      protocol: TCP
#      targetPort: 8443
#      name: https
    - nodePort: 8101
      port: 8101
  selector:
    app: openhab

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: openhab-pv-volume
  labels:
    type: local
    app: openhab
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    #path: "/mnt/data"
    path: "/home/dhiego/openhab"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openhab-pv-claim
  labels:
    app: openhab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
