apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:

        - name: pgadmin4
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "dhiego.silva@hotmail.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "f4x4d8p6"
            #              valueFrom:
#                secretKeyRef:
#                  name: pgadmin-secret
#                  key: pgadmin-default-password
            - name: PGADMIN_PORT
              value: "80"
          ports:
            - containerPort: 80
              name: pgadminport
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: [ "sh", "-c", "chown -R 5050:5050 /var/lib/pgadmin" ]
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin

      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: NodePort
#  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30003

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgadmin-pv-volume
#  namespace: pgadmin
  labels:
    type: local
    app: pgadmin
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin-pv-claim
#  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
